### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)

### ISSUE THREAD

**Issue by sayam93** [rhasspy/wyoming-openwakeword#19]
The openwakeword script probably needs an update because when I run the following command:

git clone https://github.com/rhasspy/wyoming-openwakeword.git
cd wyoming-openwakeword
script/setup

I get this error towards the end:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)
ERROR: No matching distribution found for tflite-runtime-nightly
Traceback (most recent call last):
  File "/home/pi/wyoming-openwakeword/script/setup", line 26, in <module>
    subprocess.check_call(pip + ["install", "-r", str(_PROGRAM_DIR / "requirements.txt")])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/pi/wyoming-openwakeword/.venv/bin/python3', '-m', 'pip', 'install', '-r', '/home/pi/wyoming-openwakeword/requirements.txt']' returned non-zero exit status 1.

Please help!

**Comment by sajov** [comment]
Facing same issue on PI3

**Comment by supernerd76** [comment]
Seeing the same issue on newly built pi-zero 2Ws:

Successfully installed setuptools-69.5.1 wheel-0.43.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)
ERROR: No matching distribution found for tflite-runtime-nightly
Traceback (most recent call last):
  File "/app/wyoming-openwakeword/script/setup", line 26, in <module>
    subprocess.check_call(pip + ["install", "-r", str(_PROGRAM_DIR / "requirements.txt")])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/wyoming-openwakeword/.venv/bin/python3', '-m', 'pip', 'install', '-r', '/app/wyoming-openwakeword/requirements.txt']' returned non-zero exit status 1.

**Comment by sayam93** [comment]
> Seeing the same issue on newly built pi-zero 2Ws:
> 
> Successfully installed setuptools-69.5.1 wheel-0.43.0 Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none) ERROR: No matching distribution found for tflite-runtime-nightly Traceback (most recent call last): File "/app/wyoming-openwakeword/script/setup", line 26, in subprocess.check_call(pip + ["install", "-r", str(_PROGRAM_DIR / "requirements.txt")]) File "/usr/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/app/wyoming-openwakeword/.venv/bin/python3', '-m', 'pip', 'install', '-r', '/app/wyoming-openwakeword/requirements.txt']' returned non-zero exit status 1.

just do the following:

git clone https://github.com/rhasspy/wyoming-openwakeword.git
cd ~/wyoming-openwakeword

then run
sudo nano requirements.txt

Change ‘tflite-runtime-nightly’ to ‘tflite-runtime’

script/setup.
