### ISSUE TITLE
Missing Wyoming Module - Causes Fatal Error

### ISSUE THREAD

**Issue by JupiterStar45** [rhasspy/wyoming-openwakeword#22]
ModuleNotFoundError: No module named 'wyoming'
from wyoming.server import AsyncServer

There should be a wyoming folder that has server.py somewhere. but I couldnt find it. This is why it is causing fatal error.
I couldn't even get it local wake word service started. 
Did Author removed the folder or files? Please help.

May 10 00:56:50 satellite1 systemd[1]: Started Wyoming openWakeWord.
May 10 00:56:50 satellite1 run[938]: Traceback (most recent call last):
May 10 00:56:50 satellite1 run[938]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
May 10 00:56:50 satellite1 run[938]:     return _run_code(code, main_globals, None,
May 10 00:56:50 satellite1 run[938]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
May 10 00:56:50 satellite1 run[938]:     exec(code, run_globals)
May 10 00:56:50 satellite1 run[938]:   File "/home/user/wyoming-openwakeword/wyoming_openwakeword/__main__.py", line 9, in <module>
May 10 00:56:50 satellite1 run[938]:     from wyoming.server import AsyncServer
May 10 00:56:50 satellite1 run[938]: ModuleNotFoundError: No module named 'wyoming'
May 10 00:56:51 satellite1 run[937]: Traceback (most recent call last):
May 10 00:56:51 satellite1 run[937]:   File "/home/user/wyoming-openwakeword/script/run", line 12, in <module>
May 10 00:56:51 satellite1 run[937]:     subprocess.check_call([context.env_exe, "-m", "wyoming_openwakeword"] + sys.argv[1:])
May 10 00:56:51 satellite1 run[937]:   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
May 10 00:56:51 satellite1 run[937]:     raise CalledProcessError(retcode, cmd)
May 10 00:56:51 satellite1 run[937]: subprocess.CalledProcessError: Command '['/home/user/wyoming-openwakeword/.venv/bin/python3', '-m', 'wyoming_openwakeword', '--uri', 'tcp://127.0.0.1:10400']' returned non-zero exit status 1.

**Comment by JupiterStar45** [comment]
found the reason for this and fixed it completely. closing thread

**Comment by tannisroot** [comment]
> found the reason for this and fixed it completely. closing thread

You didn't close it
