### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by monogoat** [rhasspy/wyoming-openwakeword#4]
Running in a docker, the Wyoming integration in Home Assistant is unable to connect using the IP and Port. It just says failed to connect.

Here is the docker setup:

docker run
  -d
  --name='OpenWakeWord'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="OpenWakeWord"
  -l net.unraid.docker.managed=dockerman
  -p '10400:10300/tcp'
  -v '/mnt/disks/ADATA_SX8200PNP_2J1420145469/appdata/openwakeword/custom':'/custom':'rw,slave'
  -v '/mnt/disks/ADATA_SX8200PNP_2J1420145469/appdata/openwakeword/data':'/data':'rw,slave' 'rhasspy/wyoming-openwakeword'
  --preload-model 'ok_nabu'
  --custom-model-dir /custom

**Comment by monogoat** [comment]
Looking at the other issue, I don't think it is starting properly. The log just says INFO:root:Ready.

**Comment by jkuettner** [comment]
You are mapping port `10400` to the container-port `10300`, but openwakeword is listening on `10400`. So i think you have to change the line:

```
-p '10400:10300/tcp'
```
to
```
-p '10400:10400/tcp'
```

**Comment by monogoat** [comment]
I wondered why it was the same as Whisper when the docker first ran, because I didn't set it. I am just realizing it was because I used the whisper template and it pulled that internal port over lol. If it was in a text box I would have figured it out, but I had to delete the port assignment and make a new one.

Thanks, it is connected now. Was driving me nuts.
